local Colors = {
    Light = {
        ButtonBackground = Color3.fromRGB(239, 240, 241),
        HoverBackground = Color3.fromHex('#EEEEEF'),
        TextColor = Color3.fromHex('#28292D'),
        TextColor2 = Color3.fromHex('#5E5E5E'),
        Accent = Color3.fromHex('#3c64fa'),
        ButtonActive = Color3.fromHex('#f4f4f5'),
        Shadow = Color3.new(0),
    },
    Dark = {
        ButtonBackground = Color3.fromHex('#3f3f41'),
        HoverBackground = Color3.fromHex('#38393a'),
        TextColor = Color3.fromHex('#E2E4E8'),
        TextColor2 = Color3.fromHex('#A9A9A9'),
        Accent = Color3.fromHex('#3c64fa'),
        ButtonActive = Color3.fromHex('#414243'),
        Shadow = Color3.new(1, 1, 1),
    },
}

return Colors
